services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - mssqlvolume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
     image: mcr.microsoft.com/mssql/server:2022-latest
     volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     depends_on:
        sqlserver:
          condition: service_healthy
     command: >
        bash -c "/opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Password123 -C -d master -i /docker-entrypoint-initdb.d/init.sql && echo 'All done!'"

volumes:
  mssqlvolume: