services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-dp
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - mssqlvolume:/var/lib/mssql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sql-network

volumes:
  mssqlvolume:
    driver: local

networks:
  sql-network:
    driver: bridge